# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction_item',
            new_name='TransactionItem',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cust_id',
        ),
    ]
