# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0002_auto_20180405_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
